### ISSUE TITLE
make command trigger error 

### ISSUE THREAD

**Issue by Lucatronlk** [snort3/libdaq#12]
Hello Team,

When I run the make command it triggers and error ( My Linux flavor is CentOS 7) : 

fst/fst.h:178:16: error: 'const TcpHdr' has no member named 'th_flags'
 { return (tcp->th_flags & flag) == flag; }
                ^
fst/fst.h: In member function 'void FstTcpTracker::eval(const DecodeData&, bool)':
fst/fst.h:187:45: error: 'TH_SYN' was not declared in this scope
             if (c2s && is_tcp_flag_set(tcp, TH_SYN) && !is_tcp_flag_set(tcp, TH_ACK))
                                             ^
fst/fst.h:187:78: error: 'TH_ACK' was not declared in this scope
             if (c2s && is_tcp_flag_set(tcp, TH_SYN) && !is_tcp_flag_set(tcp, TH_ACK))
                                                                              ^
fst/fst.h:192:46: error: 'TH_SYN' was not declared in this scope
             if (!c2s && is_tcp_flag_set(tcp, TH_SYN | TH_ACK))
                                              ^
fst/fst.h:192:55: error: 'TH_ACK' was not declared in this scope
             if (!c2s && is_tcp_flag_set(tcp, TH_SYN | TH_ACK))
                                                       ^
fst/fst.h:197:45: error: 'TH_ACK' was not declared in this scope
             if (c2s && is_tcp_flag_set(tcp, TH_ACK) && !is_tcp_flag_set(tcp, TH_SYN))
                                             ^
fst/fst.h:197:78: error: 'TH_SYN' was not declared in this scope
             if (c2s && is_tcp_flag_set(tcp, TH_ACK) && !is_tcp_flag_set(tcp, TH_SYN))
                                                                              ^
fst/fst.h:206:38: error: 'TH_FIN' was not declared in this scope
             if (is_tcp_flag_set(tcp, TH_FIN))
                                      ^
fst/fst.h: In member function 'bool FstTcpTracker::process_bare_ack(const DecodeData&, bool)':
fst/fst.h:222:63: error: 'TH_ACK' was not declared in this scope
     if (tcp_state != TTS_ESTABLISHED || !is_tcp_flag_set(tcp, TH_ACK) || dd.tcp_data_segment)
                                                               ^
fst/fst.h:226:27: error: 'const TcpHdr' has no member named 'th_ack'
     if (SEQ_GT(ntohl(tcp->th_ack), ntohl(meta_ack_data.tcp_ack_seq_num)))
                           ^
fst/fst.h:33:30: note: in definition of macro 'SEQ_GT'
 #define SEQ_GT(a,b)  ((int)((a) - (b)) >  0)
                              ^
fst/fst.h:228:46: error: 'const TcpHdr' has no member named 'th_ack'
         meta_ack_data.tcp_ack_seq_num = tcp->th_ack;
                                              ^
fst/fst.h:229:46: error: 'const TcpHdr' has no member named 'th_win'
         meta_ack_data.tcp_window_size = tcp->th_win;
                                              ^
fst/fst.h: In member function 'bool FstTcpTracker::get_meta_ack_data(DAQ_PktTcpAckData_t&, bool)':
fst/fst.h:240:23: warning: missing initializer for member '_daq_pkt_tcp_ack_data::tcp_ack_seq_num' [-Wmissing-field-initializers]
         meta_ack_data = { };
                       ^
fst/fst.h:240:23: warning: missing initializer for member '_daq_pkt_tcp_ack_data::tcp_window_size' [-Wmissing-field-initializers]
fst/fst.h: In member function 'bool FstKey::populate(const DAQ_PktHdr_t*, const DecodeData*)':
fst/fst.h:546:29: error: 'const TcpHdr' has no member named 'th_sport'
         src_port = dd->tcp->th_sport;
                             ^
fst/fst.h:547:29: error: 'const TcpHdr' has no member named 'th_dport'
         dst_port = dd->tcp->th_dport;
                             ^
fst/fst.h:552:29: error: 'const UdpHdr' has no member named 'uh_sport'
         src_port = dd->udp->uh_sport;
                             ^
fst/fst.h:553:29: error: 'const UdpHdr' has no member named 'uh_dport'
         dst_port = dd->udp->uh_dport;
                             ^
fst/daq_fst.cc: At global scope:
fst/daq_fst.cc:88:25: warning: missing initializer for member 'FstMsgPool::pool' [-Wmissing-field-initializers]
     FstMsgPool pool = { };
                         ^
fst/daq_fst.cc:88:25: warning: missing initializer for member 'FstMsgPool::freelist' [-Wmissing-field-initializers]
fst/daq_fst.cc:88:25: warning: missing initializer for member 'FstMsgPool::info' [-Wmissing-field-initializers]
make[1]: *** [fst/fst_libdaq_static_fst_la-daq_fst.lo] Error 1
make[1]: Leaving directory `/root/libdaq/modules'
make: *** [install-recursive] Error 1

**Comment by Xiche** [comment]
Sorry, CentOS 7 is not currently a supported platform.

**Comment by CaledoniaProject** [comment]
Field th_off is only defined when __FAVOR_BSD is set, and it's not a disto-specific problem.

To resolve this problem, just add one line in `example/netinet_compat.h`

```
#define __FAVOR_BSD
#include <netinet/tcp.h>
```

**Comment by Xiche** [comment]
(A) __FAVOR_BSD was never meant to be directly defined (it was supposed to be a side effect of defining _BSD_SOURCE and not being tempted by various other normal definitions like _GNU_SOURCE/_POSIX_SOURCE).
(B) The __FAVOR_BSD code was removed from glibc in 2013 (https://sourceware.org/git/?p=glibc.git;a=commit;h=7011c2622fe3e10a29dbe74f06aaebd07710127d), so I don't think we're too interested in supporting that scenario.
