### ISSUE TITLE
few errors with libdaq-3.0.3 

### ISSUE THREAD

**Issue by bboxzhen** [snort3/libdaq#14]
- debain8 3.16.0-10-686-pae
- Libdaq3 compiles and supports netmap has been wrong but daq 2.0.7 does

![image](https://user-images.githubusercontent.com/39783629/123910964-bdb11200-d9ad-11eb-8326-6f48fec3ec77.png)
![image](https://user-images.githubusercontent.com/39783629/123910911-af62f600-d9ad-11eb-9d09-e3e7107b5d30.png)

- daq 2.0.7

![image](https://user-images.githubusercontent.com/39783629/123911347-462fb280-d9ae-11eb-9f2a-45e7d6c638c0.png)
![image](https://user-images.githubusercontent.com/39783629/123911356-4a5bd000-d9ae-11eb-83d2-f301752f56e6.png)

- libdaq-3.0.3 

![image](https://user-images.githubusercontent.com/39783629/123910844-98240880-d9ad-11eb-90af-71172d012265.png)
![image](https://user-images.githubusercontent.com/39783629/123910856-9e19e980-d9ad-11eb-8b07-daeb4958149b.png)

**Comment by Xiche** [comment]
config.log is going to have the answers as to what it doesn't like on your system.

**Comment by Xiche** [comment]
Honestly more of a bug in netmap.h for not being properly self-contained, but I've opened PR #16 to address this issue and also fix building with netmap headers installed in a non-standard location.

**Comment by alohl669** [comment]
> Honestly more of a bug in netmap.h for not being properly self-contained, but I've opened PR #16 to address this issue and also fix building with netmap headers installed in a non-standard location.

I'm in the same situation as @bboxzhen and I can see that your PR has been frozen from 2021.

I have built netmap using a git clone from its repository and they show only one release. What could be the better way to build libdaq at this point? cloning your PR or maybe downloading a previous version of netmap?

**Comment by snortadmin** [comment]
It has been merged and will be pushed here with the next regular release.
