### ISSUE TITLE
There is no ./configure file

### ISSUE THREAD

**Issue by RubinXnibu** [snort3/libdaq#15]
The first step in the "Build and Install" instructions in README.md state to run "./configure" -- but there is no such file in either the v3.0.5 release nor the master.   I suggest putting the "./bootstrap" instruction BEFORE the "./configure" instruction.

**Comment by Xiche** [comment]
Building from git is the special case for most people, so the bootstrapping section was given second billing intentionally.  (I'm glad you were able to find that instruction as that's what you originally opened this issue about.)
