### ISSUE TITLE
Error in building libdaq

### ISSUE THREAD

**Issue by MeghShetty** [snort3/libdaq#18]
Hello, I have cloned the git repo on my pc and as well in docker. I am getting the following error when I run ./bootstrap.  am I missing any package that I have to install? Thank you in advance. 
'''
root@c9435c7e7551:/snort/libdaq# ./bootstrap
+ autoreconf -ivf --warnings=all
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --warnings=all -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force --warnings=all
configure.ac:133: error: possibly undefined macro: AC_CHECK_HEADERS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:152: error: possibly undefined macro: AC_MSG_WARN
configure:18282: error: possibly undefined macro: dnl
configure:18287: error: possibly undefined macro: AS_IF
autoreconf: /usr/bin/autoconf failed with exit status: 1
'''

**Comment by snortadmin** [comment]
See this: https://github.com/snort3/libdaq/issues/2.

**Comment by MeghShetty** [comment]
@snortadmin  Thanks for the update but I am running into any other error
''' 
config.status: error: cannot find input file: `api/Makefile.in'
'''

**Comment by MeghShetty** [comment]
Thank for the update. The solution worked but I ran into error while "make" and "./configure"
I had to make changes in the extension  for Makefile.in as the extension was Makefile.am in (api, example and test) after these changes the "./configure" worked. 
when running "make"
""
root@c935125affd3:/snort-source-files/libdaq# make
make  all-recursive
make[1]: Entering directory '/snort-source-files/libdaq'
Making all in api
make[2]: Entering directory '/snort-source-files/libdaq/api'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/snort-source-files/libdaq/api'
make[1]: *** [Makefile:539: all-recursive] Error 1
make[1]: Leaving directory '/snort-source-files/libdaq'
make: *** [Makefile:426: all] Error 2
"""
this is the error I am getting

**Comment by snortadmin** [comment]
That's is not normal. Maybe your repo is modified or your tool chain is out of date? Try again like this and see what happens:
```
mkdir -p test/build/
cd test/
git clone https://github.com/snort3/libdaq.git
cd libdaq
./bootstrap
cd ../build
../libdaq/configure --prefix=`pwd`
make install

**Comment by MeghShetty** [comment]
Worked with ubuntu without any issues but debian it failed thank you for the help.

**Comment by Xiche** [comment]
The Makefile.in files are generated from the Makefile.am files by way of automake and autoconf.  Renaming the .am files to .in files would end very poorly, as you saw.
