### ISSUE TITLE
error: possibly undefined macro: AC_CHECK_HEADERS

### ISSUE THREAD

**Issue by syedkhizarulhaq-cis** [snort3/libdaq#2]
Hi,

I have been getting the below error after running ./bootstrap:
autoreconf: running: /usr/bin/autoconf --force --warnings=all
configure.ac:133: error: possibly undefined macro: AC_CHECK_HEADERS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:152: error: possibly undefined macro: AC_MSG_WARN
configure:18244: error: possibly undefined macro: dnl
configure:18249: error: possibly undefined macro: AS_IF
autoreconf: /usr/bin/autoconf failed with exit status: 1

Thanks.

**Comment by Xiche** [comment]
You need to have pkg-config installed.
