### ISSUE TITLE
./configure missing from libdaq-master 

### ISSUE THREAD

**Issue by rkangabe** [snort3/libdaq#4]
After downloading master.zip, below is the output. I am unable to run ./configure because it does not exist. Kindly assist.

Output
----------------------------------------------------
root@ucu-monitor-01:/snort_src/libdaq-master# ls -l
total 116
drwxr-xr-x  2 root root  4096 Aug 20 18:54 api
-rwxr-xr-x  1 root root    50 Aug 20 18:54 bootstrap
-rw-r--r--  1 root root 13956 Aug 20 18:54 ChangeLog-2.x
-rw-r--r--  1 root root 14092 Aug 20 18:54 configure.ac
-rw-r--r--  1 root root 21108 Aug 20 18:54 COPYING
drwxr-xr-x  2 root root  4096 Aug 20 18:54 example
-rw-r--r--  1 root root   281 Aug 20 18:54 libdaq.pc.in
-rw-r--r--  1 root root 21108 Aug 20 18:54 LICENSE
drwxr-xr-x  2 root root  4096 Aug 20 18:54 m4
-rw-r--r--  1 root root   215 Aug 20 18:54 Makefile.am
drwxr-xr-x 11 root root  4096 Aug 20 18:54 modules
-rw-r--r--  1 root root   747 Aug 20 18:54 README.md
drwxr-xr-x  2 root root  4096 Aug 20 18:54 test

root@ucu-monitor-01:/snort_src/libdaq-master# ./configure
bash: ./configure: No such file or directory
root@ucu-monitor-01:/snort_src/libdaq-master#

**Comment by snortadmin** [comment]
Check the README:


If building from git, you will need to do the following to generate the configure script prior to running the steps above:

./bootstrap

**Comment by rkangabe** [comment]
built from git and used ./bootstrap
