### ISSUE TITLE
somthings is error

### ISSUE THREAD

**Issue by zhousodo** [snort3/libdaq#8]
a@zhou-machine:~/snort_src/libdaq$ ./bootstrap 
+ autoreconf -ivf --warnings=all
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --warnings=all -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '../..'.
libtoolize: copying file '../../ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force --warnings=all
autoreconf: running: /usr/bin/autoheader --force --warnings=all
autoreconf: running: automake --add-missing --copy --force-missing --warnings=all
configure.ac:29: installing './ar-lib'
configure.ac:26: installing './compile'
configure.ac:34: installing './config.guess'
configure.ac:34: installing './config.sub'
configure.ac:19: installing './install-sh'
configure.ac:34: error: required file './ltmain.sh' not found
configure.ac:19: installing './missing'
api/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1

**Comment by Xiche** [comment]
>       configure.ac:34: error: required file './ltmain.sh' not found

That is the error.  You should figure out why libtoolize on your system is copying it to a different location:

>       libtoolize: putting auxiliary files in '../..'.
>       libtoolize: copying file '../../ltmain.sh'

A normal run would look like this:
```
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
```
